# Generated by Django 3.1.2 on 2021-01-15 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('id_tablero', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('nombre_equipo', models.CharField(max_length=256)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fases',
            fields=[
                ('id_fases', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fases', models.CharField(max_length=256)),
                ('fecha_registro', models.DateField(default=datetime.datetime.now)),
                ('id_usuario', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_rol', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_usuario_tablero',
            fields=[
                ('id_rol_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_tablero', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('id_rol', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id_tablero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=256)),
                ('estado', models.CharField(choices=[('Iniciado', 'Iniciado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Iniciado', max_length=15)),
                ('visibilidad', models.CharField(choices=[('Privado', 'Privado'), ('Público', 'Público')], default='Privado', max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(default=datetime.datetime.now)),
                ('fecha_limite', models.DateField()),
                ('nombre_tarjeta', models.CharField(max_length=256)),
                ('id_usuario', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Usuario',
            fields=[
                ('id_tarjeta_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_tarjeta', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateField(default=datetime.datetime.now)),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('correo', models.CharField(max_length=256)),
                ('usuario', models.CharField(max_length=256)),
                ('contrasenha', models.CharField(max_length=256)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('usuario',), name='unique_usuario_usuario'),
        ),
        migrations.AddConstraint(
            model_name='tarjeta_usuario',
            constraint=models.UniqueConstraint(fields=('id_tarjeta', 'id_usuario', 'estado'), name='unique_idtarjetaidusuario_tarjeta_usuario'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id_fases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.fases'),
        ),
        migrations.AddConstraint(
            model_name='tablero',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_nombre_tablero'),
        ),
        migrations.AddConstraint(
            model_name='rol_usuario_tablero',
            constraint=models.UniqueConstraint(fields=('id_tablero', 'id_usuario', 'id_rol', 'estado'), name='unique_idtableroidusuarioidrol_rol_usuario_tablero'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('tipo_rol',), name='unique_tipo_rol_Rol'),
        ),
        migrations.AddField(
            model_name='fases',
            name='id_tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.tablero'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('nombre_equipo',), name='unique_nombre_equipo_equipo'),
        ),
    ]
