# Generated by Django 3.1.2 on 2020-10-03 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id_tablero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Iniciado', 'Iniciado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Iniciado', max_length=15)),
                ('visibilidad', models.CharField(max_length=256)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
