# Generated by Django 3.1.2 on 2020-10-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tablero',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_nombre_tablero'),
        ),
    ]
