# Generated by Django 3.1.2 on 2020-10-05 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0002_auto_20201003_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('fechaNacimiento', models.DateField()),
                ('fechaRegistro', models.DateField(default=datetime.datetime.now)),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('correo', models.CharField(max_length=256)),
                ('usuario', models.CharField(max_length=256)),
                ('contrasenha', models.CharField(max_length=256)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Iniciado', max_length=15)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('usuario',), name='unique_usuario_usuario'),
        ),
    ]
