# Generated by Django 3.1.2 on 2021-01-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0002_auto_20210116_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='id_tablero',
            new_name='id_usuario',
        ),
    ]
