# Generated by Django 3.1.2 on 2020-10-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0003_auto_20201004_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol_usuario_tablero',
            fields=[
                ('idRolUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('idTablero', models.IntegerField()),
                ('idUsuario', models.IntegerField()),
                ('idRol', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='rol_usuario_tablero',
            constraint=models.UniqueConstraint(fields=('idTablero',), name='unique_idTablero_Rol_usuario_tablero'),
        ),
        migrations.AddConstraint(
            model_name='rol_usuario_tablero',
            constraint=models.UniqueConstraint(fields=('idUsuario',), name='unique_idUsuario_Rol_usuario_tablero'),
        ),
        migrations.AddConstraint(
            model_name='rol_usuario_tablero',
            constraint=models.UniqueConstraint(fields=('idRol',), name='unique_idRol_Rol_usuario_tablero'),
        ),
    ]
