# Generated by Django 3.1.2 on 2021-01-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0003_auto_20210116_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta_usuario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.usuario'),
        ),
    ]
