# Generated by Django 3.1.2 on 2020-10-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0004_auto_20201004_2308'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rol_usuario_tablero',
            name='unique_idTablero_Rol_usuario_tablero',
        ),
        migrations.RemoveConstraint(
            model_name='rol_usuario_tablero',
            name='unique_idUsuario_Rol_usuario_tablero',
        ),
        migrations.RemoveConstraint(
            model_name='rol_usuario_tablero',
            name='unique_idRol_Rol_usuario_tablero',
        ),
        migrations.AddConstraint(
            model_name='rol_usuario_tablero',
            constraint=models.UniqueConstraint(fields=('idTablero', 'idUsuario', 'idRol'), name='unique_idTableroidUsuarioidRol_Rol_usuario_tablero'),
        ),
    ]
