# Generated by Django 3.1.2 on 2020-10-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0005_auto_20201004_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('idTablero', models.IntegerField()),
                ('idUsuario', models.IntegerField()),
                ('nombreEquipo', models.CharField(max_length=256)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('tipoRol', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Usuario',
            fields=[
                ('idTarjetaUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('idTarjeta', models.IntegerField()),
                ('idUsuario', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='rol_usuario_tablero',
            name='unique_idTableroidUsuarioidRol_Rol_usuario_tablero',
        ),
        migrations.RenameField(
            model_name='tablero',
            old_name='fecha_modificacion',
            new_name='fechaModificacion',
        ),
        migrations.RenameField(
            model_name='tablero',
            old_name='id_tablero',
            new_name='idTablero',
        ),
        migrations.AlterField(
            model_name='tablero',
            name='descripcion',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='nombre',
            field=models.CharField(max_length=256),
        ),
        migrations.AddConstraint(
            model_name='rol_usuario_tablero',
            constraint=models.UniqueConstraint(fields=('idTablero', 'idUsuario', 'idRol', 'estado'), name='unique_idTableroidUsuarioidRol_Rol_usuario_tablero'),
        ),
        migrations.AddConstraint(
            model_name='tarjeta_usuario',
            constraint=models.UniqueConstraint(fields=('idTarjeta', 'idUsuario', 'estado'), name='unique_idTarjetaidUsuario_Tarjeta_Usuario'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('tipoRol',), name='unique_TipoRol_Rol'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('nombreEquipo',), name='unique_nombreEquipo_equipo'),
        ),
    ]
