# Generated by Django 3.1.2 on 2021-01-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0005_tarjeta_usuario_nombre_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta_usuario',
            name='nombre_encargado',
        ),
    ]
