# Generated by Django 3.1.2 on 2020-10-05 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0006_auto_20201004_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('idFases', models.AutoField(primary_key=True, serialize=False)),
                ('nombreFases', models.CharField(max_length=256)),
                ('fechaRegistro', models.DateField(default=datetime.datetime.now)),
                ('fechaLimite', models.DateField()),
                ('nombreTarjeta', models.CharField(max_length=256)),
                ('idUsuario', models.IntegerField()),
                ('idTarjeta', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
    ]
