# Generated by Django 3.1.2 on 2021-01-18 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tableros', '0006_remove_tarjeta_usuario_nombre_encargado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tarjeta_usuario',
            name='unique_idtarjetaidusuario_tarjeta_usuario',
        ),
        migrations.AlterField(
            model_name='tarjeta_usuario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tarjeta_usuario',
            constraint=models.UniqueConstraint(fields=('id_tarjeta', 'id_usuario'), name='unique_idtarjetaidusuario_tarjeta_usuario'),
        ),
    ]
