# Generated by Django 3.1.2 on 2020-10-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0009_auto_20201005_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
    ]
