# Generated by Django 3.1.2 on 2020-10-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0009_auto_20201005_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='visibilidad',
            field=models.CharField(choices=[('Privado', 'Privado'), ('Público', 'Público')], default='Privado', max_length=15),
        ),
    ]
