# Generated by Django 3.1.2 on 2020-10-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0010_auto_20201026_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fases',
            name='fecha_limite',
        ),
    ]
