# Generated by Django 3.1.2 on 2020-10-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0011_remove_fases_fecha_limite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fases',
            name='nombre_tarjeta',
        ),
    ]
