# Generated by Django 3.1.2 on 2020-10-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0011_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
    ]
