# Generated by Django 3.1.2 on 2020-10-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0012_remove_fases_nombre_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fases',
            name='id_tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.tablero'),
        ),
    ]
