# Generated by Django 3.1.2 on 2020-10-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0010_auto_20201019_1329'),
        ('tableros', '0013_auto_20201026_1335'),
    ]

    operations = [
    ]
