# Generated by Django 3.1.2 on 2020-10-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0014_merge_20201028_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Pendiente', 'Pendiente')], default='Activo', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='tarjeta',
            constraint=models.UniqueConstraint(fields=('id_tarjeta', 'id_usuario', 'estado'), name='unique_idtarjetaidusuario_tarjeta'),
        ),
    ]
