# Generated by Django 3.1.2 on 2020-10-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0014_merge_20201027_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='descripcion',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id_tablero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tableros.tablero'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Pendiente', 'Pendiente')], default='Activo', max_length=15),
        ),
    ]
