# Generated by Django 3.1.2 on 2020-10-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0015_auto_20201028_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Pendiente', 'Pendiente')], default='Activo', max_length=15),
        ),
    ]
