# Generated by Django 3.1.2 on 2020-10-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0015_auto_20201028_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='descripcion_tarjeta',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
