# Generated by Django 3.1.2 on 2020-10-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0015_auto_20201028_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='id_usuario',
        ),
    ]
