# Generated by Django 3.1.2 on 2021-01-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0014_merge_20201228_1741'),
        ('tableros', '0016_auto_20201028_1532'),
    ]

    operations = [
    ]
