# Generated by Django 3.1.2 on 2020-10-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0016_remove_tarjeta_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
