# Generated by Django 3.1.2 on 2020-10-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0016_tarjeta_descripcion_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='identificador_tablero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
