# Generated by Django 3.1.2 on 2021-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0017_merge_20210115_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='id_usuario',
            new_name='id_fases',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='id_tablero',
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
    ]
