# Generated by Django 3.1.2 on 2021-01-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0018_auto_20210115_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='id_fases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableros.fases'),
        ),
    ]
